### ISSUE TITLE
Field components should support type property

### ISSUE THREAD

**Issue by maartendra** [mariusespejo/semantic-redux-form-fields#2] opened 2018-09-15 13:33 UTC
This code, 

```js
import { Field } from 'semantic-redux-form-fields';

let LoginForm = props => {
  const { handleSubmit } = props;

  return (
    <Form onSubmit={handleSubmit}>
        <Field.Input
          label='Email'
          name='email'
          type='email'
        />
    </Form>
  )
};
```

Generates this error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ConnectedField`.
```

This works though, but I prefer the shorthand style 👍 :
```js
import { Field } from 'redux-form';
import { FormInput } from 'semantic-redux-form-fields';

let LoginForm = props => {
  const { error, handleSubmit } = props;

  return (
    <Form onSubmit={handleSubmit}>
      <Form.Field>
        <Field
          label='Email'
          name='email'
          type='email'
          component={FormInput}
          type='email'
        />
      </Form.Field>
    </Form>
  )
};
```

**Comment by mariusespejo** [comment] 2018-09-15 20:24
@maartendraijer the proper way to do that shorthand is like this

```
<Field.Input name="fieldName" label="Label" />
```

which is the shorthand for providing the prop `component={FormInput}`
you're missing the `.Input` in your example which is why it isn't able to tell what type of field it is

**Comment by maartendra** [comment] 2018-09-16 19:17
@mariusespejo, thanks for your answer.

Unfortunately that generates the same error. I have updated the issue.

**Comment by mariusespejo** [comment] 2018-09-17 16:44
@maartendraijer there multiple examples of the shorthand syntax working as expected here: https://mariusespejo.github.io/semantic-redux-form-fields/index.html#field

If you can provide me with a working codesandbox example that shows that error I can take a further look, but I used this library myself in my projects and I don't have that problem. There is a good chance you have a minor typo somewhere.

**Comment by maartendra** [comment] 2018-09-25 16:16
@mariusespejo I figured it is because of the `type='email'` property. If I remove that, it's working again.

Providing any `type` property to `Field.Input` throws above error.

**Comment by mariusespejo** [comment] 2018-09-25 18:19
@maartendraijer  ah okay, you didn't have `type` in your original example which is why I couldn't pinpoint the problem. It does bring up a good point that `type` as a prop should be supported (or at least in general forwarded down to the underlying redux-form `Field` component. The problem is I used the prop `type` as a way to do the dynamic type changing like with `Field.Input`. I'll make sure to update that to using a different prop name so that `type` can still be used

**Comment by mariusespejo** [comment] 2018-09-25 20:19
this should be fixed in the most recent published version. The `type` prop is no longer used internally in this codebase so if you use it, it will just get passed down to the underlying redux-form `Field` component.

**Closed as completed by mariusespejo** 2018-09-25 20:19 UTC

**Comment by maartendra** [comment] 2018-09-25 20:23
Confirmed! Thanks @mariusespejo! 🎉
